# Generated by Django 3.2 on 2023-10-15 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.IntegerField(choices=[(0, 'Tapes'), (1, 'GLues'), (2, 'Grids'), (3, 'Gloves')], default=0),
        ),
    ]
