# Generated by Django 3.2 on 2023-10-15 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.IntegerField(choices=[(0, 'Tapes'), (1, 'Glues'), (2, 'Grids'), (3, 'Gloves')], default=0),
        ),
    ]
